server {
    listen 80;

    location /api/ {
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /opt/overpass/cgi-bin/$fastcgi_script_name;
        include fastcgi_params;
    }
}
