server {
    listen 8080;

    access_log /opt/overpass/log/nginx_access.log;
    error_log  /opt/overpass/log/nginx_error.log;

    client_body_temp_path /opt/overpass/run;
    fastcgi_temp_path     /opt/overpass/run;

    location ~ ^/api/(.*)$ {
        fastcgi_pass unix:/opt/overpass/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /opt/overpass/cgi-bin/$fastcgi_script_name;
        include fastcgi_params;
    }
}
